
# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration
client_id = "372e23d7a3ed87299b4083570479a122"
name = "dawny-pro"
handle = "dawny-pro"
application_url = "https://dawnypro.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
dev_store_url = "https://dawny-pro.myshopify.com"

[webhooks]
api_version = "2025-04"
  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"
  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "write_themes,read_themes,write_script_tags,read_script_tags,write_shop_data,read_shop_data"

[auth]
redirect_urls = ["https://dawnypro.com/auth/callback", "https://dawnypro.com/auth/shopify/callback"]

[pos]
embedded = false

[app_proxy]
url = "https://dawnypro.com"
